TAB script-binding uosc/toggle-ui
SPACE cycle pause
LEFT seek -5
RIGHT seek 5
Shift+LEFT seek -30
Shift+RIGHT seek 30
UP add volume 5
DOWN add volume -5
m cycle mute
[ add speed -0.1
] add speed 0.1
\\ set speed 1
q quit-watch-later
s screenshot video
S screenshot window
Ctrl+1 apply-profile quality; show-text "Nyx quality profile"
Ctrl+2 apply-profile performance; show-text "Nyx performance profile"
i script-binding stats/display-stats-toggle
