profile=fast
vo=gpu
hwdec=auto-safe
video-sync=display-resample
osc=yes
osd-bar=yes
keep-open=yes
save-position-on-quit=yes
volume=70
volume-max=130
slang=zh-CN,zh,chi,zho,en
alang=zh-CN,zh,chi,zho,en
screenshot-directory=~~/screenshots
cache=yes
audio-file-auto=fuzzy
sub-auto=fuzzy
script-opts-append=ytdl_hook-ytdl_path=~~/bin/yt-dlp

[quality]
profile-desc=NyxNiri quality profile
profile=high-quality
deband=yes
interpolation=yes

[performance]
profile-desc=NyxNiri battery profile
profile=fast
hwdec=auto-safe
interpolation=no
deband=no
